// Package web holds the playground page to the same standard as everything else: the
// examples it offers are the project's own tested programs, and the page is driven in a
// real browser against the corpus's expected output.
//
// docs/spec/10-examples.md is normative for the examples. The end-to-end cases are derived
// from it (tests/e2e/README.md says so), they are the programs the whole suite already runs
// on three engines at three optimization levels, and their expected output is on disk. So
// the playground offers those files rather than a second copy of the same programs, which
// is the only arrangement in which "the examples still work" is something a test can know.
package web

import (
	"fmt"
	"os"
	"path/filepath"
	"strconv"
	"strings"
	"testing"

	"github.com/scarypheonix/meta/internal/testutil"
)

// examples are the worked examples of docs/spec/10-examples.md, in its order, named for a
// reader rather than for a test runner, with two of the corpus's own programs added at the
// front: the first thing someone wants after printing is to read something back (§18), and
// the second is a list (§13). Both are end-to-end cases like every other entry here.
//
// §17's word-frequency report is deliberately absent: it reads its input from a file, and on
// a host with no filesystem it correctly prints an I/O error (ADR-0033). That is the right
// behaviour and a poor first thing to show someone, so the playground does not offer it.
var examples = []struct{ title, name string }{
	{"Hello", "hello"},
	{"Ask a question", "ask_a_question"},
	{"Lists and loops", "lists_and_loops"},
	{"Recursive fibonacci", "fib"},
	{"Closure counter", "closure_counter"},
	{"Recursive enum: a linked list", "linked_list"},
	{"Mutual recursion", "mutual_recursion"},
	{"Generics with a trait bound", "generics_ord"},
	{"Integer overflow traps", "overflow_traps"},
	{"Explicit wrapping", "wrapping_and_casts"},
	{"Result and ?", "result_and_try"},
	{"Mutation through an alias", "aliasing"},
	{"for over an iterator", "for_loop"},
	{"Green threads and channels", "thread_spawn_and_join"},
	{"A discarded allocation loop is reclaimed", "gc_reclaims_discarded_allocations"},
}

const generatedPath = "web/examples.js"

// TestExamplesFileIsCurrent regenerates the page's example list from the corpus and fails if
// what is committed differs.
//
// It is the golden-file arrangement the rest of the project uses, for the same reason: the
// page is static and cannot read tests/e2e at load time, so the alternative to generating
// this file is maintaining a second copy of thirteen programs by hand and discovering it has
// drifted when someone reports that an example no longer compiles.
//
//	UPDATE_GOLDEN=1 go test ./tests/web/
func TestExamplesFileIsCurrent(t *testing.T) {
	root := testutil.RepoRoot(t)
	want := renderExamples(t, root)
	path := filepath.Join(root, generatedPath)

	if os.Getenv("UPDATE_GOLDEN") == "1" {
		if err := os.WriteFile(path, []byte(want), 0o644); err != nil {
			t.Fatalf("writing %s: %v", generatedPath, err)
		}
		t.Logf("rewrote %s", generatedPath)
		return
	}

	got, err := os.ReadFile(path)
	if err != nil {
		t.Fatalf("reading %s: %v\nregenerate it with: UPDATE_GOLDEN=1 go test ./tests/web/", generatedPath, err)
	}
	if string(got) != want {
		t.Errorf("%s is out of date with tests/e2e/cases.\n"+
			"Regenerate it: UPDATE_GOLDEN=1 go test ./tests/web/", generatedPath)
	}
}

func renderExamples(t *testing.T, root string) string {
	t.Helper()
	var b strings.Builder
	b.WriteString("// Generated by tests/web/examples_test.go. Do not edit.\n")
	b.WriteString("//\n")
	b.WriteString("// The worked examples of docs/spec/10-examples.md, taken from the end-to-end cases\n")
	b.WriteString("// derived from it, so that every program the playground offers is one the suite\n")
	b.WriteString("// already runs on three engines at three optimization levels.\n")
	b.WriteString("//\n")
	b.WriteString("// Regenerate: UPDATE_GOLDEN=1 go test ./tests/web/\n")
	b.WriteString("window.originExamples = [\n")
	for _, e := range examples {
		src := readCase(t, root, e.name, ".origin")
		// A case that reads standard input brings its own, so choosing it from the
		// playground's list gives a program that runs rather than one that reads nothing
		// and looks broken (spec/18-input.md).
		stdin := ""
		if raw, err := os.ReadFile(filepath.Join(root, "tests", "e2e", "cases", e.name+".in")); err == nil {
			stdin = string(raw)
		}
		fmt.Fprintf(&b, "  { title: %s, name: %s, source: %s, stdin: %s },\n",
			jsString(e.title), jsString(e.name), jsString(src), jsString(stdin))
	}
	b.WriteString("];\n")
	return b.String()
}

func readCase(t *testing.T, root, name, ext string) string {
	t.Helper()
	p := filepath.Join(root, "tests", "e2e", "cases", name+ext)
	raw, err := os.ReadFile(p)
	if err != nil {
		t.Fatalf("reading %s: %v", p, err)
	}
	return string(raw)
}

// expectation is a case's expected result, read from the same companion files tests/e2e
// compares against.
type expectation struct {
	stdout string
	stderr string
	exit   int
}

func expectationFor(t *testing.T, root, name string) expectation {
	t.Helper()
	stem := filepath.Join(root, "tests", "e2e", "cases", name)
	e := expectation{stdout: readCase(t, root, name, ".out")}
	raw, err := os.ReadFile(stem + ".exit")
	if err != nil {
		t.Fatalf("reading %s.exit: %v", name, err)
	}
	code, err := strconv.Atoi(strings.TrimSpace(string(raw)))
	if err != nil {
		t.Fatalf("%s.exit is not an integer: %q", name, raw)
	}
	e.exit = code
	if raw, err := os.ReadFile(stem + ".err"); err == nil {
		e.stderr = string(raw)
	}
	return e
}

// jsString renders a Go string as a JavaScript string literal. It escapes rather than using
// a template literal because Origin source contains backslashes and `\(...)` interpolation,
// both of which a template literal would interpret.
func jsString(s string) string {
	var b strings.Builder
	b.WriteByte('"')
	for _, r := range s {
		switch r {
		case '"':
			b.WriteString(`\"`)
		case '\\':
			b.WriteString(`\\`)
		case '\n':
			b.WriteString(`\n`)
		case '\r':
			b.WriteString(`\r`)
		case '\t':
			b.WriteString(`\t`)
		default:
			if r < 0x20 {
				fmt.Fprintf(&b, `\u%04x`, r)
				continue
			}
			b.WriteRune(r)
		}
	}
	b.WriteByte('"')
	return b.String()
}

// TestEveryExampleIsCoveredByTheWasmDifferential is what lets the browser test run three
// programs instead of twenty-six.
//
// The argument for that cut is that tests/wasm already runs every example through this exact
// module on both engines, against these same golden files. That argument holds only while
// every example is a program tests/wasm actually runs, and the one class it excludes is the
// programs that use std::fs (ADR-0033: on a host with no filesystem their output is expected
// to differ, so they are named exclusions there).
//
// So this checks the condition directly, on the source. Add an example that reads or writes a
// file and this fails, which is the moment to decide whether the browser test should cover it
// rather than the moment to discover the coverage was assumed.
func TestEveryExampleIsCoveredByTheWasmDifferential(t *testing.T) {
	root := testutil.RepoRoot(t)
	// The prelude's file interface (spec/15-files.md) and the four operations under it.
	fsUses := []string{"fs::", "read_to_string", "write_string", "file_exists"}

	for _, e := range examples {
		src := readCase(t, root, e.name, ".origin")
		for _, use := range fsUses {
			if strings.Contains(src, use) {
				t.Errorf("example %q uses %s, so tests/wasm excludes it and does not check its "+
					"output on either engine. The browser test runs only three programs on the "+
					"strength of that coverage; either drop this example or widen browserRuns.",
					e.name, use)
			}
		}
		// A generated example that is not a corpus case has no golden files, so nothing
		// anywhere would notice it breaking.
		if _, err := os.Stat(filepath.Join(root, "tests", "e2e", "cases", e.name+".out")); err != nil {
			t.Errorf("example %q has no tests/e2e golden output: %v", e.name, err)
		}
	}
}
